[workspace]
resolver = "2"
members = [
    "api",
    "vupdate",
]

[workspace.dependencies]
anyhow = { version = "1" }
http = { version = "1" }
reqwest = { version = "0.11.24", default-features = false }
serde = { version = "1.0" }
serde_json = { version = "1.0" }
serde_with = { version = "3.6.0" }
tokio = { version = "1", features = ["full"] }
thiserror = { version = "1.0" }