[package]
name = "vu-api"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at
# https://doc.rust-lang.org/cargo/reference/manifest.html
[features]
client = ["reqwest"]


[dependencies]
http = { workspace = true }
reqwest = { workspace = true, optional = true,  default-features = false, features = ["json"] }
serde = { workspace = true, features = ["derive"] }
serde_with = { workspace = true, features = ["macros"] }
thiserror = { workspace = true }